language: java

jdk:
  - openjdk7
  - oraclejdk8

env:
  matrix:
    - COMPILE_VERSION=java7-compile
    - COMPILE_VERSION=java8-compile
    
matrix:
  exclude:
    - jdk: openjdk7
      env: COMPILE_VERSION=java8-compile
    - jdk: oraclejdk8
      env: COMPILE_VERSION=java7-compile
  
before_install: 
  # So that Travis CI does not ignore Java Maven Invoker class option.
  # See https://github.com/travis-ci/travis-ci/issues/1689
  - sudo rm /etc/mavenrc
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: "mvn clean test -P ${COMPILE_VERSION}"

notifications:
  email:
    on_success: always