language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
  
# So that Travis CI does not ignore Java Maven Invoker class option.
# See https://github.com/travis-ci/travis-ci/issues/1689
before_install: sudo rm /etc/mavenrc