addons:  
  firefox: "53.0.3"

language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - COMPILE_VERSION=java7-compile,!java8-compile
    - COMPILE_VERSION=java8-compile,!java7-compile
    
matrix:
  exclude:
    - jdk: oraclejdk8
      env: COMPILE_VERSION=java7-compile,!java8-compile
  
before_install: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: "mvn clean test -P ${COMPILE_VERSION}"

notifications:
  email:
    on_success: always
