language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8

env:
  matrix:
    - COMPILE_VERSION=java6-compile
    - COMPILE_VERSION=java7-compile
    - COMPILE_VERSION=java8-compile
    
matrix:
  exclude:
    - jdk: openjdk6
      env: COMPILE_VERSION=java7-compile
    - jdk: openjdk6
      env: COMPILE_VERSION=java8-compile
    - jdk: openjdk7
      env: COMPILE_VERSION=java8-compile
    - jdk: oraclejdk8
      env: COMPILE_VERSION=java7-compile
  
# So that Travis CI does not ignore Java Maven Invoker class option.
# See https://github.com/travis-ci/travis-ci/issues/1689
before_install: sudo rm /etc/mavenrc


script: "mvn clean test -P ${COMPILE_VERSION}"